/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "Clock.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "USBFS.h"
#include "USBFS_audio.h"
#include "USBFS_cdc.h"
#include "USBFS_hid.h"
#include "USBFS_midi.h"
#include "USBFS_pvt.h"
#include "USBFS_cydmac.h"
#include "USBFS_msc.h"
#include "SS_aliases.h"
#include "SS.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "DSP_reset_aliases.h"
#include "DSP_reset.h"
#include "GND_aliases.h"
#include "GND.h"
#include "I2S_1.h"
#include "I2S_1_PVT.h"
#include "I2S_Clock.h"
#include "MISO_S_aliases.h"
#include "MISO_S.h"
#include "MOSI_S_aliases.h"
#include "MOSI_S.h"
#include "SCLK_S_aliases.h"
#include "SCLK_S.h"
#include "SPIS.h"
#include "SPIS_PVT.h"
#include "SS_S_aliases.h"
#include "SS_S.h"
#include "Clock_SPISlave.h"
#include "LED_aliases.h"
#include "LED.h"
#include "TxDma_dma.h"
#include "spi_rx_interrupt.h"
#include "DmaDone.h"
#include "USBFS_Dm_aliases.h"
#include "USBFS_Dm.h"
#include "USBFS_Dp_aliases.h"
#include "USBFS_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

