/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Current_Source_aliases.h"
#include "Current_Source.h"
#include "Pin_Ground_aliases.h"
#include "Pin_Ground.h"
#include "Mux0_0_aliases.h"
#include "Mux0_0.h"
#include "Mux0_1_aliases.h"
#include "Mux0_1.h"
#include "Mux0_2_aliases.h"
#include "Mux0_2.h"
#include "Mux0_3_aliases.h"
#include "Mux0_3.h"
#include "Mux1_0_aliases.h"
#include "Mux1_0.h"
#include "Mux1_1_aliases.h"
#include "Mux1_1.h"
#include "Mux1_2_aliases.h"
#include "Mux1_2.h"
#include "Mux1_3_aliases.h"
#include "Mux1_3.h"
#include "IDAC8.h"
#include "ADC_SAR_1.h"
#include "AMux_1.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "Clock.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "SS_aliases.h"
#include "SS.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "LCD_Char.h"
#include "ADC_SAR_0.h"
#include "AMux_0.h"
#include "Clock_out_aliases.h"
#include "Clock_out.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "LCD_Char_LCDPort_aliases.h"
#include "LCD_Char_LCDPort.h"
#include "ADC_SAR_0_IRQ.h"
#include "ADC_SAR_0_theACLK.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

