/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD_Char.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "SPIS.h"
#include "SPIS_PVT.h"
#include "SS_1_aliases.h"
#include "SS_1.h"
#include "Dev_mosi_aliases.h"
#include "Dev_mosi.h"
#include "Dev_sclk_aliases.h"
#include "Dev_sclk.h"
#include "Dev_ss_aliases.h"
#include "Dev_ss.h"
#include "Dev_miso_aliases.h"
#include "Dev_miso.h"
#include "Dev_GND_aliases.h"
#include "Dev_GND.h"
#include "LCD_Char_LCDPort_aliases.h"
#include "LCD_Char_LCDPort.h"
#include "SPIS_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

