/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "CapSense_1.h"
#include "CapSense_1_CSHL.h"
#include "CapSense_1_Pins.h"
#include "CapSense_1_TunerHelper.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "SS_aliases.h"
#include "SS.h"
#include "SPI_Clock.h"
#include "LED_aliases.h"
#include "LED.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "CapSense_1_CompCH0.h"
#include "CapSense_1_IdacCH0.h"
#include "CapSense_1_AMuxCH0.h"
#include "CapSense_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

